// Curated local model catalog for sd.cpp
// All models must be publicly available (no auth required)

// Shared auxiliary files needed by Z-Image type models
const ZIMAGE_AUXILIARY = {
    llm: {
        id: '__llm__',
        filename: 'Qwen3-4B-Instruct-2507-UD-Q4_K_XL.gguf',
        displayName: 'Qwen3-4B Text Encoder',
        sizeGB: 2.4,
        downloadUrl: 'https://huggingface.co/unsloth/Qwen3-4B-Instruct-2507-GGUF/resolve/main/Qwen3-4B-Instruct-2507-UD-Q4_K_XL.gguf',
    },
    vae: {
        id: '__vae__',
        filename: 'ae.safetensors',
        displayName: 'FLUX VAE',
        sizeGB: 0.33,
        downloadUrl: 'https://huggingface.co/Comfy-Org/z_image_turbo/resolve/main/split_files/vae/ae.safetensors',
    },
};

const LOCAL_MODEL_CATALOG = [
    // ── Z-Image (Tongyi-MAI) — native sd.cpp GGUF support ──────────────────
    // Requires auxiliary files: Qwen3-4B LLM text encoder + FLUX VAE
    {
        id: 'z-image-turbo',
        name: 'Z-Image Turbo',
        description: 'WaveSpeed\'s featured local model — ultra-fast 8-step generation. No API key needed. Requires text encoder + VAE (~2.7 GB extra).',
        type: 'z-image',
        filename: 'z_image_turbo-Q4_K.gguf',
        sizeGB: 2.5,
        downloadUrl: 'https://huggingface.co/leejet/Z-Image-Turbo-GGUF/resolve/main/z_image_turbo-Q4_K.gguf',
        aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16'],
        defaultWidth: 1024,
        defaultHeight: 1024,
        defaultSteps: 8,
        defaultGuidance: 1.0,
        sampler: 'euler',
        scheduler: 'simple',
        tags: ['turbo', 'fast', 'local', 'featured'],
        featured: true,
        requiresAuxiliary: true,
    },
    {
        id: 'z-image-base',
        name: 'Z-Image Base',
        description: 'Full-quality model from Tongyi-MAI — higher detail, 50-step generation. Requires text encoder + VAE (~2.7 GB extra).',
        type: 'z-image',
        filename: 'z-image-Q4_K_M.gguf',
        sizeGB: 3.5,
        downloadUrl: 'https://huggingface.co/unsloth/Z-Image-GGUF/resolve/main/z-image-Q4_K_M.gguf',
        aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16'],
        defaultWidth: 1024,
        defaultHeight: 1024,
        defaultSteps: 50,
        defaultGuidance: 7.5,
        sampler: 'euler',
        scheduler: 'simple',
        tags: ['high-quality', 'local', 'detailed'],
        featured: true,
        requiresAuxiliary: true,
    },
    // ── Classic SD 1.5 models ───────────────────────────────────────────────
    {
        id: 'dreamshaper-8',
        name: 'Dreamshaper 8',
        description: 'Versatile SD 1.5 model — great for portraits, landscapes, and artistic styles.',
        type: 'sd1',
        filename: 'DreamShaper_8_pruned.safetensors',
        sizeGB: 2.1,
        downloadUrl: 'https://huggingface.co/Lykon/DreamShaper/resolve/main/DreamShaper_8_pruned.safetensors',
        aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16'],
        defaultWidth: 512,
        defaultHeight: 512,
        defaultSteps: 20,
        defaultGuidance: 7.5,
        sampler: 'euler_a',
        tags: ['photorealistic', 'artistic', 'versatile'],
    },
    {
        id: 'realistic-vision-v51',
        name: 'Realistic Vision v5.1',
        description: 'Highly photorealistic people and scenes, based on SD 1.5.',
        type: 'sd1',
        filename: 'realisticVisionV51_v51VAE.safetensors',
        sizeGB: 2.1,
        downloadUrl: 'https://huggingface.co/SG161222/Realistic_Vision_V5.1_noVAE/resolve/main/Realistic_Vision_V5.1_fp16-no-ema.safetensors',
        aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16'],
        defaultWidth: 512,
        defaultHeight: 768,
        defaultSteps: 25,
        defaultGuidance: 7,
        sampler: 'euler_a',
        tags: ['photorealistic', 'portraits', 'people'],
    },
    {
        id: 'anything-v5',
        name: 'Anything v5',
        description: 'High quality anime and illustration style image generation.',
        type: 'sd1',
        filename: 'Anything-v5.0-PRT.safetensors',
        sizeGB: 2.1,
        downloadUrl: 'https://huggingface.co/Yntec/AnythingV5/resolve/main/Anything-v5.0-PRT.safetensors',
        aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16'],
        defaultWidth: 512,
        defaultHeight: 768,
        defaultSteps: 20,
        defaultGuidance: 7,
        sampler: 'euler_a',
        tags: ['anime', 'illustration', 'artistic'],
    },
    // ── SDXL ───────────────────────────────────────────────────────────────
    {
        id: 'stable-diffusion-xl-base',
        name: 'SDXL Base 1.0',
        description: 'Official Stable Diffusion XL base model — higher resolution, excellent quality.',
        type: 'sdxl',
        filename: 'sd_xl_base_1.0.safetensors',
        sizeGB: 6.9,
        downloadUrl: 'https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors',
        aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16'],
        defaultWidth: 1024,
        defaultHeight: 1024,
        defaultSteps: 30,
        defaultGuidance: 7.5,
        sampler: 'dpmpp2m',
        tags: ['sdxl', 'high-quality', 'versatile'],
    },
];

module.exports = { LOCAL_MODEL_CATALOG, ZIMAGE_AUXILIARY };
